### ISSUE TITLE
jsonl为空

### ISSUE THREAD

**Issue by nuoma** [MIracleyin/mmdp_mnbvc#1]
首先有个地方要改一下。Traceback (most recent call last):
  File "examples/process_text/main.py", line 139, in <module>
    main()
  File "examples/process_text/main.py", line 136, in main
    logger.info(f"{args.pdf_dir}: all {r}, error {f}")
AttributeError: 'Namespace' object has no attribute 'pdf_dir'

麻烦，我跟着setup教程，然后运行命令后，过了几秒就结束了，jsonl是空的，过程如下：
(mmdp) ma@a800:/data/mn/code/mmda_mnbvc/mmdp_mnbvc$ python examples/process_text/main.py --pdfs_dir ../pdf/ --jsonl_path parse.jsonl --mnbvc_format
/data/mn/anaconda3/envs/mmdp/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.2 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/data/mn/anaconda3/envs/mmdp/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator MaxAbsScaler from version 1.2.2 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/data/mn/anaconda3/envs/mmdp/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator LinearSVC from version 1.2.2 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

**Comment by MIracleyin** [comment]
您好，感谢您的关注，代码已经修复。
您的第二个问题可能是由于 sklearn 版本问题。

**Comment by nuoma** [comment]
非常感谢！
如果我理解的没错的话，mnbvc是希望用这个代码把可选择的pdf转化成为jsonl。但是我看了一下allenai的原始项目，似乎用pdfplumber进行解析的话，对于原文档内的一些表格，数学化学符号公式，都会有比较大的影响，结果就贼差。

我这边是有一部分内部的电子书（化工类的可选择pdf）想洗出来脱敏以后发给mnbvc，但是这个问题没想明白就不好往下走。同时看了一下书生万卷里面有一些教科书的，很干净的markdown格式，但是我同样把pdf转成word再用pandoc转md，结果并不好。不知道您有没有什么想法。

**Comment by MIracleyin** [comment]
目前 PDF 解析项目仅实现纯文档解析，复杂PDF（如书籍正在排期处理），这边欢迎加入 mnbvc，可以一起尝试解决👏👏

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nuoma** [comment]
好的，贡献过一点语料。唯一联系方式是MNBVC@253874.net对吗

**Comment by MIracleyin** [comment]
是的，可以留言提供数据，有相关技能也可以加入一起处理。
目前这个 issue 我就关闭了，感谢您的关注。
